[server]
headless = true
address = "localhost"
port = 5000

[theme]
primaryColor = "#4a69bd"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F9FAFB"
textColor = "#2c3e50"
font = "sans serif"
